-- awlworknsewplay_dyes_com

return {
    siteName = "awlworknsewplay.com/dyes",
    description = getText("UI_MailOrderCatalogs_SiteDescription_AwlWorkAndSewPlayComDyes"),
    items = {
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A bold scarlet red industrial dye for your bloodiest creations.",
            colorName = "Scarlet Red",
            rgb = {0.69, 0.08, 0.11},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A vibrant tangerine orange dye, perfect for warning signs or fashion statements.",
            colorName = "Tangerine Orange",
            rgb = {1.0, 0.4, 0.2},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Brighten your world with this brilliant yellow industrial dye.",
            colorName = "Brilliant Yellow",
            rgb = {1.0, 0.93, 0.02},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Kelly green dye ideal for military fatigues or rugged outerwear.",
            colorName = "Kelly Green",
            rgb = {0.2, 0.4, 0.09},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Deep forest green dye for stealthy camo or woodland fashion.",
            colorName = "Forest Green",
            rgb = {0.06, 0.16, 0.04},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A regal royal blue dye for uniforms and prestigious garb.",
            colorName = "Royal Blue",
            rgb = {0.0, 0.16, 0.49},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A deep and brooding midnight blue for dark, rich textiles.",
            colorName = "Midnight Blue",
            rgb = {0.33, 0.47, 0.67},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A nautical navy blue dye for traditional workwear or uniforms.",
            colorName = "Navy Blue",
            rgb = {0.04, 0.11, 0.38},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Dark plum dye for a rich, mysterious aesthetic.",
            colorName = "Dark Plum",
            rgb = {0.25, 0.01, 0.23},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Soft and subtle beige dye, great for neutral tones and accents.",
            colorName = "Beige",
            rgb = {0.87, 0.75, 0.4},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Earthy tan beige dye for understated, rugged gear.",
            colorName = "Tan Beige",
            rgb = {0.76, 0.51, 0.38},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Classic brown dye for vintage leather looks and earthy tones.",
            colorName = "Brown",
            rgb = {0.55, 0.45, 0.39},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Dark brown dye, perfect for heavy-duty wear and gothic aesthetics.",
            colorName = "Dark Brown",
            rgb = {0.11, 0.09, 0.04},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Charcoal grey dye for industrial and modernist styles.",
            colorName = "Charcoal Grey",
            rgb = {0.19, 0.24, 0.25},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Absolute black dye for the deepest, darkest tones.",
            colorName = "Black",
            rgb = {0.02, 0.02, 0.02},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Wonder Whitener adds brilliant brightness or lightens other dyes.",
            colorName = "Wonder Whitener",
            rgb = {1.0, 1.0, 1.0},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A rich and royal purple dye for bold statement pieces.",
            colorName = "Purple",
            rgb = {0.25, 0.0, 0.23},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Electric fuschia dye for loud, expressive designs.",
            colorName = "Fuschia",
            rgb = {0.67, 0.11, 0.49},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A vivid cardinal red dye, perfect for striking visuals.",
            colorName = "Cardinal Red",
            rgb = {0.56, 0.02, 0.11},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Golden anilene yellow for glowing, vintage effects.",
            colorName = "Anilene Yellow",
            rgb = {1.0, 0.71, 0.07},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A bold alizarin crimson dye for historic, artistic flair.",
            colorName = "Alizarin",
            rgb = {0.67, 0.12, 0.15},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A vivid anilene purple dye, inspired by the original mauvine.",
            colorName = "Anilene Purple",
            rgb = {0.57, 0.0, 0.98},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Gentian violet dye, with deep herbal and floral tones.",
            colorName = "Gentian Violet",
            rgb = {0.33, 0.26, 0.46},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A classic malachite green for rich, emerald-inspired hues.",
            colorName = "Malachite Green",
            rgb = {0.24, 0.48, 0.43},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Deep pigment blue 61 dye for aquatic or atmospheric palettes.",
            colorName = "Pigment Blue 61",
            rgb = {0.0, 0.13, 0.62},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Basic violet 4 for bright, punchy purple highlights.",
            colorName = "Basic Violet 4",
            rgb = {0.42, 0.0, 0.43},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "A dusky yet vibrant purple dye from the basic violet 3 family.",
            colorName = "Basic Violet 3",
            rgb = {0.27, 0.11, 0.48},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Brilliant Victoria Blue BO for luminous blue accents.",
            colorName = "Victoria Blue BO",
            rgb = {0.04, 0.26, 0.69},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "High-impact Brilliant Blue FCF dye for eye-catching applications.",
            colorName = "Brilliant Blue FCF",
            rgb = {0.02, 0.42, 0.92},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Pure red dye for a powerful feeling.",
            colorName = "Pure Red",
            rgb = {1.0, 0.0, 0.0},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Pure green dye for natural, vivid saturation.",
            colorName = "Pure Green",
            rgb = {0.0, 1.0, 0.0},
        },
        {
            name = "Base.IndustrialDye",
            price = 20,
            description = "Pure blue dye for a reliable and bold look.",
            colorName = "Pure Blue",
            rgb = {0.0, 0.0, 1.0},
        },
    }
}
